### ISSUE TITLE
highlighted text is white (not visible)

### ISSUE THREAD

**Issue by fennecinspace** [EliverLara/Ant-Bloody#2]
hello, 
i'm on Cinnamon 3.6.4 on linux Mint 18.3
i have an issue in the desktop only (not in the file manager (nemo))
when i highlight a text when renaming icons it appears this way
![](https://i.imgur.com/fGuDJ32.png)

**Comment by EliverLara** [comment]
Hi, I have not tested the theme under cinnamon, so let me check it and hopefully I'll  fix it  soon.

**Comment by sreeramp96** [comment]
not supporting in ubuntu 18.04 
![screenshot from 2018-04-27 11-39-57](https://user-images.githubusercontent.com/16064120/39347304-d6298b7c-4a0f-11e8-9092-c76b44e9c423.png)
![screenshot from 2018-04-27 11-40-29](https://user-images.githubusercontent.com/16064120/39347305-d661a232-4a0f-11e8-965d-07ad2e8d1943.png)
![screenshot from 2018-04-27 11-40-38](https://user-images.githubusercontent.com/16064120/39347307-d69f0898-4a0f-11e8-9c75-d4698b8a1a1c.png)

**Comment by fennecinspace** [comment]
unsolved .. will close.
