### ISSUE TITLE
Linux Mint 19 Tara beta.

### ISSUE THREAD

**Issue by DarienRamcharan** [EliverLara/Ant-Bloody#3]
Linux Mint 19 has a new layout when you install themes. There is a new " Windows Border " tab and it would be used to install the Mac Osx like Cancel,maximize and minimize buttons but it Ant doesn't show up there. 
![image](https://user-images.githubusercontent.com/22904082/41387670-2b84294a-6f56-11e8-9864-7a78aed3f98b.png)

**Comment by LogX7** [comment]
what do you mean ? i've never seen this tab you're talking about ?
