### ISSUE TITLE
Window control craziness?

### ISSUE THREAD

**Issue by josephsamela** [EliverLara/Ant-Bloody#5]
I'm using Pop!_OS 18.10 with Gnome 3.30.1. The "maximize" window control button is missing...except when the the window is non-focused, then all buttons appear...but they're all gray. Also when switching window focus the buttons pop and stretch? Here's a gif to show what's happening.

![peek 2018-11-21 18-32](https://user-images.githubusercontent.com/16111451/48873496-24183180-edbc-11e8-9561-c4d811e6d241.gif)

Other than this minor issue, this theme looks great! Thank you!

**Comment by josephsamela** [comment]
For now, I switched to the "standard-button" version of this theme - window control buttons behave as expected.

**Comment by EliverLara** [comment]
Hi, Are you using a hidpi display?

**Comment by josephsamela** [comment]
Yes, scaling at 200%

**Comment by EliverLara** [comment]
It should be fixed with the last commit, could you confirm that please?

**Comment by josephsamela** [comment]
Seems to work great. Thanks for the fix!

![peek 2018-11-26 21-00](https://user-images.githubusercontent.com/16111451/49053523-72fc0780-f1be-11e8-8e9e-d2d730aad334.gif)
