### ISSUE TITLE
VS CODE NO MENU BAR

### ISSUE THREAD

**Issue by fennecinspace** [EliverLara/Ant-Bloody#6]
![image](https://user-images.githubusercontent.com/9774613/49546998-dc2bfb00-f8e1-11e8-8d46-31f8dbefa668.png)

**Comment by EliverLara** [comment]
Hi, that's a common issue in newer vscode versions, check [here](https://code.visualstudio.com/docs/setup/linux#_low-contrast-menu-bar) for details.
